add example of get() function
JuliaData/DataTables.jl pull request #32
Opened 2017-03-11 09:56 UTC by FredSoftwares

very usefull to extract the value from the Nullable wrapper.

2017-03-11 10:03 UTC, nalimilan requested changes
Thanks. Could you also add a reference to the manual? http://docs.julialang.org/en/stable/manual/types/#nullable-types-representing-missing-values

2017-03-11 10:03 UTC, nalimilan commented on docs/src/man/getting_started.md
> +The get() function is very usefull to extract the value from the Nullable wrapper.
I would just say "can be used to". `Nullable` should be in backticks. Also mention "when it is not null".

2017-03-11 10:03 UTC, nalimilan commented on docs/src/man/getting_started.md
> +
One line break is enough.

2017-03-11 10:03 UTC, nalimilan commented on docs/src/man/getting_started.md
> +julia> b = Dates.DateTime(get(a), "HH:MM:SS")
No need to introduce date/time functionalities here. Just show that the `String` value can be extracted.

2017-03-11 10:19 UTC, nalimilan commented on docs/src/man/getting_started.md
> +example :
Missing initial upper case. Also, better not create a new paragraph just for this word.

2017-03-11 10:19 UTC, nalimilan commented on docs/src/man/getting_started.md
> +julia> a = Nullable{String}("14:00:00")
`{String}` isn't needed here.

2017-03-11 10:19 UTC, nalimilan commented on docs/src/man/getting_started.md
> +julia> c = get(a)
Call this `b`?

2017-03-11 10:20 UTC, nalimilan commented on docs/src/man/getting_started.md
> +The get() function can be used to extract the value from the `Nullable` wrapper.
Ah, and missing backticks around `get`. Also I think in general the parentheses are omitted.

2017-03-11 10:28 UTC, FredSoftwares commented on docs/src/man/getting_started.md
> +julia> c = get(a)
ok :) 
I did not understand what you mean by "add a reference to the manual?" do you mean I should insert a link (just paste http://docs.julialang.org/en/stable/manual/types/#nullable-types-representing-missing-values) or do I have to add the example of the get() function in the stable manual ? Sorry, I am very new to github.

2017-03-11 10:31 UTC, nalimilan commented on docs/src/man/getting_started.md
> +julia> c = get(a)
I meant adding a sentence pointing to the Julia manual for more information (the URL shouldn't appear, it should just be a link).

2017-03-11 11:47 UTC, nalimilan commented
I think you missed a few other comments I've made.

2017-03-11 20:18 UTC, nalimilan commented on docs/src/man/getting_started.md
>  julia> a = Nullable{String}("14:00:00")
`{String}` is still not needed here.

2017-03-12 04:24 UTC, ararslan approved these changes

2017-03-12 10:46 UTC, nalimilan approved these changes
Thanks @FredSoftwares!

2017-03-12 10:47 UTC, merged